version: '3'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth2
      MYSQL_USER: oauth2
      MYSQL_PASSWORD: oauth2
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

volumes:
  db_data:
    driver: local

networks:
  app_net:
    driver: bridge
